---
- name: Delete remote working directory if exists
  become: true
  file:
    state: absent
    path: '{{ remote_working_directory }}'

- name: Creates remote working directory
  become: true
  file:
    path: '{{ remote_working_directory }}'
    state: directory
    mode: 0755

- name: git clone repo
  shell: git clone https://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@github.com/terrance2630/CCC_A2.git
  args:
    chdir: '{{ remote_working_directory }}'
