- name: install python with Mastodon and CouchDB
  hosts: localhost
  become: yes
  tasks:
    - name: install Python3
      apt:
        name: python3
        state: latest

    - name: install pip
      apt:
        name: python3-pip
        state: latest

    - name: install env
      pip:
        name:
          - Mastodon.py
          - couchdb
          - scipy
          - transformers
          - nltk
          - torch
        state: latest

    - name: run Python application for au_social server
      shell: 'nohup python3 harvester.py -s au_social > au_s.log 2>&1 &'

    - name: run Python application for au server
      shell: 'nohup python3 harvester.py -s au > au.log 2>&1 &'
